### ISSUE TITLE
Fatal error: Cannot redeclare class liveshow_twitchtv

### ISSUE THREAD

**Issue by Fjolnd** [Sysix/liveshow-Addon#1]
Hey Sysix,

ich habe ein kleines Problem mit dem Addon. Ich habe das Addon bei einem Kollegen eingebaut und wenn er nun eine neue Liveshow hinzufügen möchte, kommt der Fehler. Ich habe die sc_liveshow.php jedoch in der navigation eingebunden, sprich über den content include von der Seite. Ich denke wegen dem bekomme ich diesen Fehler.

Fatal error: Cannot redeclare class liveshow_twitchtv in /kunden/376292_06406/webseiten/liveshows/twitchtv_live.php on line 52

In Line 52 ist jedoch nur ein abschließendes Tag } - denkst du, du kannst mir einen Lösungsansatz geben? Weil so muss der Kollege die <?php include ('sc_liveshow.php') ?> erst aus der index.php entfernen, um eine neue Liveshow einfügen zu können.

**Comment by Sysix** [comment]
Schau mal ob die Änderung das problem löst:
https://github.com/Sysix/liveshow-Addon/commit/3de10aa6f74f0a179e3cd1e5f1c1d1d2d93a79b2

**Comment by Fjolnd** [comment]
Hat super geklappt! Besten Dank. Kann man was gegen die Ladezeiten machen? Die Seite baut sich erst nach ca. 3 Sekunden auf und es ist bemerkbar, dass es von der sc_liveshow.php kommt.

**Comment by Sysix** [comment]
man könnte das ganze cachen. Die Frage wie lange soll der Cache aktiv bleiben.
Aber solch ein Mechanismus ist nicht im Addon intergriert.
